name: MPD_post_check_for_fpd_twn
channels:
  - defaults
  - anaconda
  
dependencies:
  - numpy==1.16.5
  - pandas==0.25.1
  - joblib==0.13.2
  - scikit-learn==0.21.3
  - pip
  - pip:
    - xgboost==0.90
    - pyodbc 